### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [cardoe/cargo-ebuild#2]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Looks like this is blocked on https://github.com/rust-lang/cargo/issues/3944. I will follow up in this issue when they have a new release ready.

**Comment by cardoe** [comment]
Looks like there's a new cargo that supports serde. I believe that's cargo 0.21 which appears to require at least Rust 1.19.0 (not due to the serde change) but I have a current requirement to work with Rust 1.15.1 still so this isn't yet workable for me.

This goes back to crates are semver but stdlib and the compiler really aren't. rust-lang/rfcs#1133
